### PR TITLE
WIP - don't merge, don't review. some renaming, code cleaning

### PR DESCRIPTION
**Pull request by Casyfill**
- cleaning
- renamed `get_combo_partition` to `execute`
- renamed `weight_prop` to `weight` to be concise and consistent with networkx
- extracted graph decomposition into a separate function
- moved misc functions into separate file `misc.py`
- Set weight by default to None.
- Checks and raises if given weight property is present in the graph (raises ValueError if not)
- added tests for graph decomposition
- turned on old test on "test known partition"

### CODE REVIEW

**Comment by Casyfill** [comment]
TODO:
split `execute` into
- execute (graph)
- execute_from_file (str)
- execute_from_array (list of tuples)
- pass `return_modularity` into C

**Comment by Alexander-Belyi** [comment]
Frankly, I wouldn't do that. This function does exactly the same thing - applies combo to the graph and returns partition. That would be a perfect case for function overloading in typed language. Keeping it as one function does some work for the user. Consider this scenario: I have a script where I call this function several times for the same graph but with different parameters. If I want just to replace my graph with modularity matrix, now I can just change one line - initialization of graph. In your case, I need to find all calls to the function and replace it with another one or write checks everywhere.

As for returning modularity, no, it's not worth it. We would need to have two versions of each function, as you cannot overload function differing only by return type. We are calculating modularity anyway and could return it from combo.run(). But this calculation is negligible compared to the whole algorithm, so it's done as a separate call for now.

**Comment by Casyfill** [comment]
Sounds good. I think it is still worth it to add one more option within the same function - to pass raw tuples (or  maybe even an array) so that networks would be optional as well. 

Just to clarify - it is not possible to overload function returns in C++?

**Comment by Casyfill** [comment]
I need to think a bit on weights - there is an edge case of some edges (pun not intended) lacking given property, so it should be set to Zero. But we also need to deal with unweighted graphs (by setting weight to 1). On my first attend doing both led to setting zero for edges in unweighted graph.

**Comment by Alexander-Belyi** [comment]
> Sounds good. I think it is still worth it to add one more option within the same function - to pass raw tuples (or maybe even an array) so that networks would be optional as well.
And as Stan mentioned in an email we will add one more option to pass modularity matrix, I assume as list of lists. So we would need to distinguish these cases either by adding another parameter, or yet by having another function.
 I'd say let's keep just one function for now, and split only if we have to.
> Just to clarify - it is not possible to overload function returns in C++?
Yes.

**Comment by Alexander-Belyi** [comment]
> I need to think a bit on weights - there is an edge case of some edges (pun not intended) lacking given property, so it should be set to Zero. But we also need to deal with unweighted graphs (by setting weight to 1). On my first attempt doing both led to setting zero for edges in unweighted graph.

When would that case arise? To me it seems like ill-formed graph and we don't have to assume such edges to have weight zero.
But if you think it's something reasonably common, then we can firstly check if at least one edge has this attribute. If that's the case, then set default weight to 0, otherwise keep it 1.

**Comment by Casyfill** [comment]
> And as Stan mentioned in an email we will add one more option to pass modularity matrix, I assume as list of lists. So we would need to distinguish these cases either by adding another parameter, or yet by having another function.
> I'd say let's keep just one function for now, and split only if we have to.

Cool. Re list of lists - we don't have to be very specific here, I hope to keep code the same for list of lists or numpy array (this should be possible given they both slice the same way.
AFAIK, there should be a way to nicely pass numpy arrays to C++ without re-building them, but not sure if this is something easy/worth it

**Comment by Casyfill** [comment]
@Alexander-Belyi I fixed default weight, import, some internals. Merging as is. Let's discuss arrays input in a separate issue

**Pull request merged**
